i3-msg "workspace Browsers, move workspace to output HDMI-0"
i3-msg "workspace Terminals, move workspace to output DVI-I-1"
i3-msg "workspace Spotify, move workspace to output DVI-I-1"
i3-msg "workspace Chats, move workspace to output DVI-I-1"
i3-msg "workspace ???, move workspace to output DVI-D-0"
i3-msg "workspace Browers"
