[[ $- != *i* ]] && return

export DOT_FILES=~/.dotfiles
export BASHRC_CONFIG_DIR=$DOT_FILES/bashrc/src

source $BASHRC_CONFIG_DIR/env_vars.sh
source $BASHRC_CONFIG_DIR/aliases.sh
source $BASHRC_CONFIG_DIR/path.sh
source $BASHRC_CONFIG_DIR/shell_options.sh
source $BASHRC_CONFIG_DIR/tab_completion.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
