source ~/.dotfiles/bashrc/src/env_vars.sh
source ~/.dotfiles/bashrc/src/aliases.sh
source ~/.dotfiles/bashrc/src/path.sh
source ~/.dotfiles/bashrc/src/tab_completion.sh

if test -e ~/.fzf.bash
  source ~/.fzf.bash
end
 
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
set -U fish_user_paths ~/.rvm/bin
if test -d ~/.rvm/scripts/rvm
   source "~/.rvm/scripts/rvm"
end
